//
// Created by nikita on 7/15/24.
//

#ifndef CARLUDGINE_INCLUDE_MODULES_NCURSES_OOP_WINDOW_HPP
#define CARLUDGINE_INCLUDE_MODULES_NCURSES_OOP_WINDOW_HPP

#endif //CARLUDGINE_INCLUDE_MODULES_NCURSES_OOP_WINDOW_HPP
